### ISSUE TITLE
Request to share the code and datasets

### ISSUE THREAD

**Issue by Nandan9911** [YasminFathy/HandleImbalancedDatasets#1]
Hello Yasmin, 

I came across your repository with reference to your paper titled - "Learning With Imbalanced Data in Smart Manufacturing: A Comparative Analysis". I request you to update the code and datasets here if possible, as I would like to review them.

Thanks and regards,
Nandan Ganguly

**Comment by YasminFathy** [comment]
Apologies that it takes ages to get back to you. I have uploaded the code.

**Comment by Nandan9911** [comment]
Hi Yasmin,

Thank you for sharing the code.

Regards,
Nandan Ganguly
